title: "Success Business Advisors"
description: "Expert accounting, tax, VAT & corporate services in Ras Al Khaimah. Get tailored financial solutions and compliance support in the UAE."
url: "https://www.sbadvisors.ae"
baseurl: ""

# SEO
locale: "en_AE"
og_image: "/assets/img/sba_advisors_banner.png"

theme: minima

permalink: pretty

exclude:
  - node_modules
  - dist
  - vendor
  - .github
  - README.md
  - Gemfile.lock

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

sass:
  sass_dir: _sass
  style: compressed   # expanded | compressed

# _config.yml
plugins:
  - jekyll-assets
  - jekyll-sitemap

assets:
  sources:
    - assets/css
    - assets/js
    - assets/img
